### ISSUE TITLE
Bug when cancelling save after calling on_closing function

### ISSUE THREAD

**Issue by PatrickBruso** [CSSG-Labs/PyNote#35]
When quitting the application, there is a bug in one circumstance I came across.  If the user receives the prompt to save changes, clicks yes to save changes, and is taken to the "save as" function to pick a file location, the user can then cancel that file dialog box, at which point the application will quit without saving.  I would suggest instead that if the user cancels the file dialog box while in the middle of saving during exiting the program, that instead the user returns to the program and the exiting is cancelled.  Otherwise, someone may mistakenly cancel out of the file dialog box when saving and then lose their work as the program immediately quits.

**Comment by ghost** [comment]
Good catch. Didn't think of it
