### ISSUE TITLE
Convert Save Button to Menu Bar

### ISSUE THREAD

**Issue by PatrickBruso** [CSSG-Labs/PyNote#4]
Currently, text is saved using the save button.  We need to convert the button to a menu bar.  For this issue, we need to code a menu bar for our application that contains "new", "open", "save", and "save as" options.  This issue is to code the menu bar itself, and not to add functionality for when a user clicks on a menu item.

**Comment by ghost** [comment]
By "menu bar" do you mean top menu bar (like, for example, in the Notepad with its | File | Edit | Format | etc ) with subitems (in this case for | File |, for example, "new", "open", "save", "save as")? And do I understand correctly that the subitems' functions for this issue should not be implemented (even though the "saveas" function already exists)? Thank you in advance

**Comment by PatrickBruso** [comment]
> By "menu bar" do you mean top menu bar (like, for example, in the Notepad with its | File | Edit | Format | etc ) with subitems (in this case for | File |, for example, "new", "open", "save", "save as")? And do I understand correctly that the subitems' functions for this issue should not be implemented (even though the "saveas" function already exists)? Thank you in advance

Yup, that is exactly correct.  Although, you can connect the saveas function to the menu item 'save as' since that function has already been implemented.  I just meant that, for this issue, you shouldn't write any of the functions for the menu items.
