### ISSUE TITLE
Let User Save with Control + s

### ISSUE THREAD

**Issue by PatrickBruso** [CSSG-Labs/PyNote#42]
To allow for quicker saving, add code to the application that will allow the user to invoke the "save" function by pressing a combination of the control key + the 's' key.  Instead of having to click File -> Save, the user can now just type 'ctrl + s' to save the file.

**Comment by gunjan-l** [comment]
Hey @PatrickBruso  ,
I'm interested in contributing to this issue, so before I start working
it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

**Comment by PatrickBruso** [comment]
Hi @9gl I don't really have any resources for this issue but I'm sure there's plenty out there.  It's fairly straightforward.  We need to watch for key-presses and, if the user presses both the "Ctrl" key and the "s" key at the same time, call the 'save' function.
