### ISSUE TITLE
Open Recent submenu

### ISSUE THREAD

**Issue by mrHeavenli** [CSSG-Labs/PyNote#46]
Common feature in most editors. It'd have a list of recently opened files(click on one to open it), and at the bottom, the option to clear the file history. I'm not sure if I should put a limit on the amount of files in the recently opened list or not. If so, I'm thinking max. 10 files.
Please tell me what you think!

**Comment by ghost** [comment]
@mrHeavenli It is a good idea. Although, in the long run the limit will be essential (imagine having a list of a 100 entries if the user decides not to bother themselves with the clearing). I'd suggest up to 5 (or at max up to 10 as you proposed) entries and also there should be either a protection mechanism or a check whether or not the listed file exists (as if not the program will most probably crash). 
I will suggest one more important in my opinion thing: it is necessary to clear first #39 as you don't "paint a possibly rusted car" if you understand what I mean

**Comment by mrHeavenli** [comment]
Project seems dead so I'm not continuing
